version: '3.4'
services:

  test:
    container_name: react-django-es-test
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./test_hosts.env
    command: ["bash", "-c",
              "python manage.py makemigrations && python manage.py migrate && pytest"]
    volumes:
      - .:/code

volumes:
  data:
