version: '3.4'
services:

  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    image: elasticsearch:6.4.0
    volumes:
      - data:/usr/share/elasticsearch/data

  test:
    container_name: react-django-es-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["./wait-for-it.sh", "elasticsearch:9200", "-t", "30", "--", "bash", "-c",
              "python manage.py makemigrations && python manage.py migrate && python manage.py test"]
    volumes:
      - .:/code
    depends_on:
      - elasticsearch

volumes:
  data:

